from sqlalchemy import ForeignKey, Index, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from icm.constants import ChangeField, InterfaceField, UserField
from icm.data.base import Base
from icm.data.constants.database import TableNames


class ChangeSchema(Base):
    """ORM schema of the `changes` table.

    A row pairs two `interfaces` rows (`id_old`/`id_new`) that were detected
    as different between two consecutive daily consults. The table is
    truncated and reinserted in full every time the updater runs, so
    `id_old`/`id_new` always reference `interfaces` rows created that same
    run (never autogenerated here).
    """

    __tablename__ = TableNames.CHANGES
    __table_args__ = (
        Index(f"ix_{TableNames.CHANGES}_{ChangeField.ASSIGNED}", ChangeField.ASSIGNED),
    )

    id_old: Mapped[int] = mapped_column(
        Integer, ForeignKey(f"{TableNames.INTERFACES}.{InterfaceField.ID}"), primary_key=True
    )
    ip_old: Mapped[str] = mapped_column(String(15), nullable=False)
    community_old: Mapped[str] = mapped_column(String, nullable=False)
    sysname_old: Mapped[str] = mapped_column(String, nullable=False)
    ifIndex_old: Mapped[int] = mapped_column(Integer, nullable=False)
    ifName_old: Mapped[str | None] = mapped_column(String, nullable=True)
    ifDescr_old: Mapped[str | None] = mapped_column(String, nullable=True)
    ifAlias_old: Mapped[str | None] = mapped_column(String, nullable=True)
    ifHighSpeed_old: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ifOperStatus_old: Mapped[str | None] = mapped_column(String(100), nullable=True)
    ifAdminStatus_old: Mapped[str | None] = mapped_column(String(100), nullable=True)

    id_new: Mapped[int] = mapped_column(
        Integer, ForeignKey(f"{TableNames.INTERFACES}.{InterfaceField.ID}"), primary_key=True
    )
    ip_new: Mapped[str] = mapped_column(String(15), nullable=False)
    community_new: Mapped[str] = mapped_column(String, nullable=False)
    sysname_new: Mapped[str] = mapped_column(String, nullable=False)
    ifIndex_new: Mapped[int] = mapped_column(Integer, nullable=False)
    ifName_new: Mapped[str | None] = mapped_column(String, nullable=True)
    ifDescr_new: Mapped[str | None] = mapped_column(String, nullable=True)
    ifAlias_new: Mapped[str | None] = mapped_column(String, nullable=True)
    ifHighSpeed_new: Mapped[int | None] = mapped_column(Integer, nullable=True)
    ifOperStatus_new: Mapped[str | None] = mapped_column(String(100), nullable=True)
    ifAdminStatus_new: Mapped[str | None] = mapped_column(String(100), nullable=True)

    assigned: Mapped[str | None] = mapped_column(
        String(100), ForeignKey(f"{TableNames.USERS}.{UserField.USERNAME}"), nullable=True, default=None
    )

    old_interface: Mapped["InterfaceSchema"] = relationship(
        "InterfaceSchema", foreign_keys=[id_old]
    )
    new_interface: Mapped["InterfaceSchema"] = relationship(
        "InterfaceSchema", foreign_keys=[id_new]
    )
    assigned_user: Mapped["UserSchema | None"] = relationship(
        "UserSchema", foreign_keys=[assigned]
    )
